config/routes.rb
MythicalWell::Application.routes.draw do

  #match 'ui(/:action)', controller: 'ui'
  resources :events, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:create, :edit, :update]
    member do
      post :watch
      post :attend
      post :unfollow
      get :watchers
      get :attendees
    end

    collection do
      get :search
    end
  end
  devise_for :users
  resources :users, only: [:show, :index] do
    member do
      get 'set_base'
      put 'update_base', :as => :set_base, :path => 'set_base'
      get 'followers'
      get 'followees'
      post 'follow'
      post 'unfollow'
      get 'follow_events'
      get 'all_events'
    end
    resources :messages, only: [:index, :destroy] do
      collection do
        post 'empty'
      end
    end
  end
  resources :tags, only: [:index]
  resources :nodes, only: [:index]

  namespace :admin do
    resources :events, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update]
    resources :nodes, except: [:show]
    resources :comments, only: [:index]
    resources :categories, except: [:show]
  end

  match '/my/events' => "users#my_events", via: :get
  match '/goto/:node' => "sessions#goto", via: :get, as: :goto
  match '/node/:short_name' => 'events#index', via: :get, as: :node
  root to: "nodes#index"
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :is_read, :user_id, :comment_id, :msg_type
  
  def self.EVENT_TYPE; 1; end
  def self.MENTION_TYPE; 2; end
  #def self.FOLLOW_EVENT_TYPE; 3; end

  belongs_to :user, :foreign_key => 'user_id'
  belongs_to :comment, :foreign_key => 'comment_id'

  scope :unread, where(:is_read => false)
  scope :recent, order("created_at DESC")
end

app/controllers/messages_controller.rb
# -*- coding: utf-8 -*-
class MessagesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  def index
    @messages = current_user.messages.includes(:comment).recent.page params[:page]
    #current_user.read_messages(@messages)
    #p @messages.first
    @messages.unread.update_all(:is_read => true)
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    redirect_to user_messages_path(current_user)
  end
  
  def empty
    @messages = current_user.messages.recent.page params[:page]   
    @messages.map(&:destroy)

    redirect_to user_messages_path(current_user)
  end
end

app/views/messages/_message_push.html.slim
= link_to "#{current_user.messages.count}消息", user_messages_path(current_user)

app/views/messages/index.html.slim
.grid_9
  .messages
    - if @messages.blank?
      | 暂无消息，想更有人气吗？ 多多去发活动、留言吧～
    - else
      = link_to "清空", empty_user_messages_path(current_user), class: 'btn btn-danger', method: :post
      ul.unstyled
        - @messages.each do |msg|
          li
            .photo = avatar_for msg.user, 48
            .content
              .title
                - if msg.msg_type == Message.EVENT_TYPE
                  h4
                    = link_to msg.comment.user.username, msg.user
                    - if msg.comment.event.user == current_user
                      | 回复了你发起的活动：
                    - else
                      | 回复了你关注的活动：
                    = link_to truncate(msg.comment.event.title, :length => 20), msg.comment.event
                - elsif msg.msg_type == Message.MENTION_TYPE
                  h4
                    = link_to msg.comment.user.username, msg.user
                    | 在
                    = link_to msg.comment.event.title, msg.comment.event
                    | @了你：

              p
                = comment_raw msg.comment.content[0..30]
            .action
              = link_to user_message_path(msg.user, msg), :method => :delete do
                i.icon-trash.icon-large
    = paginate @messages

.grid_3
  = render "users/user_sidebar", meta: {}, user: current_user