config/routes.rb
MythicalWell::Application.routes.draw do

  #match 'ui(/:action)', controller: 'ui'
  resources :events, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:create, :edit, :update]
    member do
      post :watch
      post :attend
      post :unfollow
      get :watchers
      get :attendees
    end

    collection do
      get :search
    end
  end
  devise_for :users
  resources :users, only: [:show, :index] do
    member do
      get 'set_base'
      put 'update_base', :as => :set_base, :path => 'set_base'
      get 'followers'
      get 'followees'
      post 'follow'
      post 'unfollow'
      get 'follow_events'
      get 'all_events'
    end
    resources :messages, only: [:index, :destroy] do
      collection do
        post 'empty'
      end
    end
  end
  resources :tags, only: [:index]
  resources :nodes, only: [:index]

  namespace :admin do
    resources :events, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update]
    resources :nodes, except: [:show]
    resources :comments, only: [:index]
    resources :categories, except: [:show]
  end

  match '/my/events' => "users#my_events", via: :get
  match '/goto/:node' => "sessions#goto", via: :get, as: :goto
  match '/node/:short_name' => 'events#index', via: :get, as: :node
  root to: "nodes#index"
end

app/views/layouts/admin/_header.html.slim
.navbar.navbar-inverse
  .navbar-inner
    .container
      .brand Admin
      ul.nav
        li.active = link_to "首页", root_path
        li = link_to "活动", admin_events_path
        li = link_to "用户", admin_users_path
        li = link_to '节点', admin_nodes_path
        li = link_to "评论", admin_comments_path
        li = link_to "分类", admin_categories_path
      form.navbar-search
        input.search-query type="text" placeholder="搜索"
      ul.nav.pull-right
        - if user_signed_in?
          li#messages_unread
            = link_to "#{current_user.messages.unread.count}消息", user_messages_path(current_user)
            = subscribe_to "/messages_unread/#{current_user.username}"
          li
            = link_to "我的活动", my_events_path
          li.dropdown
            = link_to "#", :class => "dropdown-toggle", :'data-toggle' => "dropdown" do
              = current_user.username
              b.caret
            ul.dropdown-menu
              li = link_to "我的主页", current_user
              li = link_to "基本资料设置", set_base_user_path(current_user)
              li = link_to "密码设置", edit_user_registration_path
              li = link_to "登出", destroy_user_session_path, :method => :delete
        - else
          li = link_to "登录", new_user_session_path
          li = link_to "注册", new_user_registration_path