config/routes.rb
MythicalWell::Application.routes.draw do

  #match 'ui(/:action)', controller: 'ui'
  resources :events, only: [:index, :show, :new, :create, :edit, :update] do
    resources :comments, only: [:create, :edit, :update]
    member do
      post :watch
      post :attend
      post :unfollow
      get :watchers
      get :attendees
    end

    collection do
      get :search
    end
  end
  devise_for :users
  resources :users, only: [:show, :index] do
    member do
      get 'set_base'
      put 'update_base', :as => :set_base, :path => 'set_base'
      get 'followers'
      get 'followees'
      post 'follow'
      post 'unfollow'
      get 'follow_events'
      get 'all_events'
    end
    resources :messages, only: [:index, :destroy] do
      collection do
        post 'empty'
      end
    end
  end
  resources :tags, only: [:index]
  resources :nodes, only: [:index]

  namespace :admin do
    resources :events, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update]
    resources :nodes, except: [:show]
    resources :comments, only: [:index]
    resources :categories, except: [:show]
  end

  match '/my/events' => "users#my_events", via: :get
  match '/goto/:node' => "sessions#goto", via: :get, as: :goto
  match '/node/:short_name' => 'events#index', via: :get, as: :node
  root to: "nodes#index"
end

app/models/event.rb
# -*- coding: utf-8 -*-
require 'file_size_validator'
class Event < ActiveRecord::Base
  attr_accessible :title, :start_date, :end_date, :date_desc, :location, :content, :category_id, :theme, :fee, :image, :tag_tokens, :node_id, :capacity
  mount_uploader :image, ImageUploader

  has_many :comments, :dependent => :destroy
  belongs_to :user, foreign_key: 'user_id'
  delegate :username, :name, :to => :user, :prefix => true, :allow_nil => true

  has_many :event_tags, :dependent => :destroy
  has_many :tags, :through => :event_tags

  has_many :event_followers
  has_many :followers, :class_name => 'User', :through => :event_followers, :order => 'event_followers.created_at DESC'

  belongs_to :node, foreign_key: 'node_id'
  delegate :name, :to => :node, :prefix => true, :allow_nil => true

  belongs_to :category, foreign_key: 'category_id'
  delegate :name, :to => :category, :prefix => true, :allow_nil => true

  validates :title, presence: {message: "标题不能为空"}
  validates :location, presence: {message: "地点不能为空"}
  validates :content, presence: {message: "活动详情不能为空"}
  validates :fee, presence: {message: "费用不能为空"}
  validates :category_id, presence: {message: "分类不能为空"}
  #validates :theme, presence: { message: "主题不能为空" }
  validates :user_id, presence: true
  validates :image, :presence => {message: "需要上传海报"}, :file_size => { :maximum => 1.megabytes.to_i, message: "文件大小必须在1M以内"}
  validates :node_id, presence: {message: '需要选择学校'}
  scope :recent, :order => 'start_date DESC'

  attr_reader :tag_tokens
  def tag_tokens=(tokens)
    self.tag_ids = Tag.ids_from_tokens(tokens)
  end

  def self.complex_find(params = {})
    nodes_arr = []
    if params[:short_name]
      node = Node.find_by_short_name(params[:short_name])
      if node.classify == 'school'
        nodes_arr = [node.id]
      elsif node.classify == 'city'
        nodes_arr = node.children.map do |ch|
          ch.classify == 'area' ? ch.children.map(&:id) : ch.id
        end.flatten
      elsif node.classify == 'area'
        nodes_arr = node.children.map(&:id)
      end
    end
    with_node = nodes_arr.empty? ? Event : Event.where(:node_id => nodes_arr)
    if params[:category]
      category = Category.find_by_name(params[:category])
      unless category.blank?
        events = with_node.where(:category_id => category.id).recent.page(params[:page])
      end
    elsif params[:tag]
      events = find_with_tag(params[:tag]).where(:node_id => nodes_arr).recent.page(params[:page]) unless nodes_arr.empty?
      events = find_with_tag(params[:tag]).recent.page(params[:page]) if nodes_arr.empty?
    else
      events = with_node.includes(:user).recent.page(params[:page])
    end
    events
  end

  def self.find_with_tag(tag)
    Tag.find_by_name(tag).events
  end

  after_destroy :delete_img
  def delete_img
    remove_image
  end

  def user_follow_type(user)
    event_followers.where(:user_id => user.id)[0].classify
  end

  def attendees
    attendship = event_followers.where(:classify => 'attend')
    followers.where(:id => attendship.map(&:user_id))
  end

  def watchers
    attendship = event_followers.where(:classify => 'watch')
    followers.where(:id => attendship.map(&:user_id))
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::ApplicationController
  def index
    @events = Event.includes(:user).includes(:tags).order('start_date DESC').page(params[:page]).per(10)
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(params[:event])
      redirect_to admin_events_path
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      redirect_to admin_events_path
    else
      redirect_to admin_events_path
    end

  end
end

app/controllers/events_controller.rb
# encoding: utf-8
class EventsController < ApplicationController
  load_and_authorize_resource :only => [:new, :edit, :update, :create, :destroy, :follow, :unfollow]
  before_filter :authenticate_user!, :only => [:new, :create, :edit, :create, :follow, :unfollow]
  def index
    # Based on tag, category, node
    @events = Event.complex_find(params)
    @events_hot = Event.recent.limit(5)
  end

  def search
    querys = params[:q].to_s.split.map{|q| "%#{q}%"}
    conditions = ["title like ? or content like ?"] * querys.length * ' or '
    querys = querys.zip(querys).flatten!
    @events = Event.where(conditions, *querys).page params[:page]
    @events_hot = Event.recent.limit(5)
    render 'index'
  end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments.order('created_at')
    @comment = Comment.new
    @events_hot = Event.recent.limit(5)
  end

  def follow
    @event = Event.find(params[:id])
    @event.followers << current_user
  end

  def unfollow
    @event = Event.find(params[:id])
    @event.followers.delete(current_user)
    redirect_to @event
  end

  def watch
    follow
    @event.event_followers.where(:user_id => current_user)[0].update_attributes(:classify => 'watch')
    redirect_to @event
  end

  def attend
    follow
    @event.event_followers.where(:user_id => current_user)[0].update_attributes(:classify => 'attend')
    redirect_to @event
  end

  def watchers
    @event = Event.find(params[:id])
    @followers = @event.watchers.page(params[:page]).per(96)
    render 'followers'
  end

  def attendees
    @event = Event.find(params[:id])
    @followers = @event.attendees.page(params[:page]).per(96)
    render 'followers'
  end

  def new
    @event = Event.new
    @schools = Node.where(:classify => ['school', 'area'])
  end

  def create
    date_handle
    @event = current_user.events.build(params[:event])

    respond_to do |format|
      if @event.save
        format.html {redirect_to @event}
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }

      end
    end
  end

  def edit
    @event = Event.find(params[:id])
    @schools = Node.where(:classify => ['school', 'area'])
  end

  def update
    date_handle

    @event = Event.find(params[:id])

    if @event.update_attributes(params[:event])
      redirect_to @event
    else
      render :edit
    end
  end

  private

  def date_handle
    t_repeat = params[:date_repeat]
    t_type = params[:date_type]
    t_desc = params[:date_desc]
    if t_repeat == 'no'
      if t_type == 'range' && t_desc.split(' - ').length > 1
        t_start = (t_desc.split(' - ')[0] +' ' + params[:start_time][0]).to_datetime
        t_end = (t_desc.split(' - ')[1] + ' ' + params[:end_time][0]).to_datetime
        params[:event][:start_date], params[:event][:end_date] = t_start, t_end
        params[:event][:date_desc] = "#{t_desc.split(' - ')[0]}到#{t_desc.split(' - ')[1]}的#{params[:start_time][0]}-#{params[:end_time][0]}"
      elsif
        t_arr = t_desc.split(', ')
        if t_arr.length == 1 || (t_type == 'range' && t_desc.split(' - ').length == 1)
          t_start = (t_desc + ' ' + params[:start_time][0]).to_datetime
          t_end = (t_desc + ' ' + params[:end_time][0]).to_datetime
          params[:event][:start_date], params[:event][:end_date] = t_start, t_end
          params[:event][:date_desc] = "#{t_desc}的#{params[:start_time][0]}-#{params[:end_time][0]}"
        else
          t_start = (t_arr[0]+' '+params[:start_time][0]).to_datetime
          t_end = (t_arr[-1] + ' ' + params[:end_time][0]).to_datetime
          params[:event][:start_date], params[:event][:end_date] = t_start, t_end
          params[:event][:date_desc] = t_arr.zip(params[:start_time].zip(params[:end_time]).map{|a| a*'到'}).map{|b| b*'的'} * ';'
        end
      end
    else
      t_begin = params[:repeat_range].split(' - ')[0]
      t_end = params[:repeat_range].split(' - ')[1]
      params[:event][:start_date] = (t_begin + ' ' + params[:start_time][0]).to_datetime
      params[:event][:end_date] = (t_end + ' ' + params[:end_time][0]).to_datetime
      repeat_arr = t_desc.split(', ').map{|t| t.to_datetime.strftime('周%u')}
      repeat_arr.map!{|t| t.gsub("周7", "周日")}
      params[:event][:date_desc] = "#{t_begin}到#{t_end}中#{repeat_arr*','}的#{params[:start_time][0]}-#{params[:end_time][0]}"
    end
    p params[:event][:start_date], params[:event][:end_date], params[:event][:date_desc]
  end
end

app/helpers/events_helper.rb
# encoding: utf-8
module EventsHelper
  def comment_raw(text)
    return "" if text.blank?
    text.gsub! /\r\n/, "<br>"
    text.gsub! /(@)(\S*\s)/, "<a href=#{root_url}users/\\2>\\1\\2</a>"
    raw text
  end

  def tag_list e
    if e.tags.any?
      raw e.tags.map{|t| link_to t.name, events_path(tag: t.name)} * ', '
    else
      ""
    end
  end

  def time_select
    options_for_select((('8'..'23').to_a+('0'..'7').to_a).map{|t| [t+':00', t+':30']}.flatten)
  end

  def date_brief desc
    return "暂无描述" if desc.blank?
    arr = desc.split(';')
    if arr.length == 1
      arr[0]
    else
      arr[0] + '等'
    end
  end

  def origin_desc event
    return "暂无描述" if event.date_desc.blank?
    event.date_desc.gsub(';', ';   ')
  end

  def events_follow_tag(event)
    return "" unless user_signed_in?
    return "" if event.blank?
    return "" if own? event
    if event.followers.include?(current_user)
      classify = event.user_follow_type(current_user) == 'watch'? '您已关注' : '您要参加'
      follow_link = link_to("取消", unfollow_event_path(event), :method => 'post')
      content_tag('span', raw("#{classify}(#{follow_link})"), class: 'label label-info')
    else
      watch_icon = content_tag("i", "", class: "icon-eye-open icon-large follow")
      attend_icon = content_tag('i', '', class: "icon-check icon-large")
      watch_link = link_to(raw(watch_icon + "  关注"), watch_event_path(event), :method => 'post')
      attend_link = link_to(raw(attend_icon + "  参加"), attend_event_path(event), :method => 'post')
      watch_link + attend_link
    end
  end

  def my_image_tag url
    if FileTest.exist?(url)
      image_tag url
    else
      p Rails.root.join('public' 'noimage.png')
      image_tag 'http://farm9.staticflickr.com/8202/8219119189_cc8c04f101.jpg'
    end
  end

end

app/views/events/_date_select.html.slim
.control-group
  label.control-label 活动时间
  .controls
    select.btn.span2.date-type name='date_type'
      option value="multi" 分散多天
      option value="range" 连续多天
    '
    select.btn.span2.date-repeat name='date_repeat'
      option value="no" 无重复
      option value="week" 每周重复
      //option value="twoweek" 每两周重复
      //option value="month" 每月重复
    input.date-desc type='hidden' name='date_desc' value=""
    p.text-warning 选择重复需要在下方选择重复的区间
    .alert.alert-info.date-show
      | 时间为：
    #calendar
    .repeat_range
      | 选择重复区间
      input#repeat_range type='text' name='repeat_range'

    table.time-select
      thead
        tr
          th 开始时间
          th 结束时间
      tbody
        tr
          td = select_tag 'start_time[]', time_select, class: 'btn span2'
          td = select_tag 'end_time[]', time_select, class: 'btn span2'
          td
            span.label.label-info = Time.now.to_date.to_s(:db)

app/views/events/_events_table.html.slim
ul.unstyled.events
  - events.each do |event|
    li.item.container_9
      .photo
        /= link_to event do
        = my_image_tag event.image_url(:show).to_s + "dasdad"
      .content
        .title = link_to truncate(event.title, :length => 20), event
        .info
          ul.unstyled
            li
              = raw "时间： #{date_brief(event.date_desc)}"
              = link_to '(详细)', '#', rel:'tooltip', data: {placement: 'right', :'original-title' => "#{event.date_desc}"}, class: 'date_desc'
            li = "学校或区域：#{event.node_name}"
            li = "地点：#{event.location}"
            li = "费用：#{event.fee}"
            li.category
              | 分类：
              = link_to event.category_name, url_for(:category => event.category_name)
            - if event.theme
              li = "主题：#{truncate(event.theme, :length => 25)}"
            li
              | 发起人：
              = link_to event.user_username, event.user
            li.tag
              | 标签：
              = tag_list event
    .clear

app/views/events/_form.html.slim
= simple_form_for event, validate: true, :html => {class:"form-horizontal", id:"create_event", :multipart => true} do |f|
  legend = meta[:legend]
  = f.input :title, label: "活动标题", input_html: {:style => 'width: 300px', maxlength: 50}
  = f.input :category_id, label: "分类", collection: Category.all.to_a, prompt: "选择分类"
  = f.input :theme, label: "主题"
  /.control-group
    = f.label :title, "活动周期", class: 'control-label'
    .controls
      = f.text_field:
  = render 'date_select'
  = f.input :node_id, label: '所在学校或区域', :collection => schools
  = f.input :location, label: "活动地点"
  = f.input :content, label: "活动详情", as: :text, input_html: {:style => "width: 700px;"}, validate: false
  script
    | $('#event_content').wysihtml5({"image": false, "color": true});
  = f.input :fee, label: "活动费用", input_html: {value: '0元/人'}
  = f.input :capacity, label: "限制人数", :hint => "不填为不限制"
  = f.input :image, label: "海报", as: :file, validate: meta[:image], hint: ""
  = f.input :tag_tokens, label: "标签", input_html: {data: {load: event.tags}}
  .form-actions
    = f.submit meta[:button], class: 'btn btn-primary', :disable_with => "正在处理"

app/views/events/_hot.html.slim
= link_to new_event_path, :class => 'create_event_link' do
  .create_event 创建活动

.box
  .title 热门活动
  ul.unstyled
    - events_hot.each do |hot|
      li = link_to truncate(hot.title, :length => 14), hot
.box
  .title 时间
  ul.unstyled
    li = link_to "三天内", "#"
    li = link_to "一周内", "#"
    li = link_to "周末", "#"
    li = link_to "更多", "#"
.box
  .title 分类
  ul.unstyled
    - Category.all.each do |cat|
      li = link_to cat.name, events_path(:category => cat.name)

app/views/events/_mini_followers.html.slim
.box.mini_event_followers
  .title
    | 活动成员
  table
    - event.followers[0..11].each_slice(4).to_a.each do |group|
      tr
        - group.each do |follower|
          td
            = link_to follower, :class => 'follower' do
              = avatar_for follower, 45
  .follower_links
    = link_to "#{event.attendees.count}人要参加", attendees_event_path(event)
    = link_to "#{event.watchers.count}人关注", watchers_event_path(event)

app/views/events/_photo.html.slim
.box.event_photo
  = my_image_tag event.image_url(:show).to_s

app/views/events/edit.html.slim
.grid_12
  .box
    == render 'form', :meta => {legend: '编辑活动', button: '确定更新', image: false}, :event => @event, :schools => @schools

app/views/events/followers.html.slim
.container_12.event_followers
  .grid_9
    .box
      table
        legend = params[:action] == 'attendees'? '参加者' : '关注者'
        - @followers.each_slice(8).to_a.each do |group|
          tr
            - group.each do |follower|
              td
                = link_to follower, :class => 'follower' do
                  = avatar_for follower, 58
                  = truncate(follower.username, :length => 10)
      = paginate @followers

  .grid_3
    .box.back
      = link_to "返回#{@event.title}", @event
    = render 'photo', :event => @event

app/views/events/index.html.slim
.grid_9
  - unless @events.blank?
    = render('events_table', events: @events)
    = paginate @events
  - else
    .box style="padding: 10px;"
      | 无活动

.grid_3
  = render 'hot', events_hot: @events_hot
.clear

app/views/events/new.html.slim
.grid_12
  .box
    == render 'form', :meta => {legend: "创建活动", button: "确定创建", image: true}, :event => @event, :schools => @schools

app/views/events/show.html.slim
.container_12
  .grid_9
    .event
      .author
        = link_to @event.user, :class => 'author_photo' do
          = avatar_for @event.user, 56
        javascript:
          $('.author_photo').tooltip({placement: 'right', title: "#{@event.user.name} @#{@event.user.username}"})
        = link_to @event.user.username, @event.user, data: {name: @event.user.name}, :class => 'none'
      h2.title = @event.title
      .tag_cat
        = link_to events_path(:category => @event.category), :class => 'category_link' do
          i.icon-tasks
          = @event.category_name
        script
          | $('.category_link').tooltip({title: '分类'})
        - @event.tags.each do |tag|
          = link_to events_path(tag: tag.name) do
            i.icon-tag
            = tag.name
      .desc
        = raw @event.content
    .event_info
      table
        tr
          td
            ul.unstyled
              li
                i.icon-calendar
                = raw "#{date_brief(@event.date_desc)}"
                = link_to '(详细)', '#', rel:'tooltip', data: {placement: 'right', :'original-title' => "#{origin_desc @event}"}, class: 'date_desc'
              li
                span style="font-weight:bold;" ￥
                '
                = "#{@event.fee}"
              - unless @event.capacity.blank?
                li
                  i.icon-group
                  = "#{@event.capacity}人"
          td
            ul.unstyled
              li
                i.icon-flag
                = "#{@event.node.name}"
              li
                i.icon-map-marker
                = "#{@event.location}"
    .event_action
      = events_follow_tag @event
      - if user_signed_in? and current_user == @event.user
        = link_to edit_event_path(@event), :class => 'edit' do
          i.icon-edit.icon-large
        script
          | $('.icon-edit').tooltip({title: '编辑'})

    #comments_list
      = render "comments/index", :event => @event

    #reply
      = render "comments/new", :event => @event, :comment => @comment

  .grid_3
    = render 'photo', :event => @event
    /= render 'hot', events_hot: @events_hot
    = render 'mini_followers', event: @event